function generatePDF() {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    // Title
    doc.setFontSize(22);
    doc.setTextColor(64, 224, 208); // Turquoise
    doc.text("BeautyOfBeaches - Travel Guide", 20, 20);

    // Intro
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text("Welcome to your ultimate guide to the world's most beautiful beaches.", 20, 30);
    doc.text("This document contains a curated list of top beaches from our website.", 20, 36);

    // Zones
    let y = 50;

    const zones = [
        { name: "North Zone", beaches: ["Reynisfjara Beach, Iceland", "Lofoten Islands, Norway", "Cannon Beach, USA", "Durness Beach, Scotland", "Long Beach, Canada"] },
        { name: "South Zone", beaches: ["Whitehaven Beach, Australia", "Bora Bora, French Polynesia", "Anse Source d'Argent, Seychelles", "Copacabana, Brazil", "Boulders Beach, South Africa"] },
        { name: "East Zone", beaches: ["Maya Bay, Thailand", "Nusa Dua, Bali", "El Nido, Philippines", "Radhanagar Beach, India", "Maldive Islands"] },
        { name: "West Zone", beaches: ["Santa Monica Beach, USA", "Tulum Beach, Mexico", "Waikiki Beach, USA", "Manuel Antonio, Costa Rica", "Navagio Beach, Greece"] }
    ];

    zones.forEach(zone => {
        if (y > 270) {
            doc.addPage();
            y = 20;
        }

        doc.setFontSize(16);
        doc.setTextColor(0, 95, 115); // Deep Blue
        doc.text(zone.name, 20, y);
        y += 10;

        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);
        zone.beaches.forEach(beach => {
            doc.text(`- ${beach}`, 30, y);
            y += 7;
        });
        y += 10;
    });

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("Generated by BeautyOfBeaches AI", 20, 290);

    doc.save("BeautyOfBeaches_Guide.pdf");
}
